apiVersion: v1
kind: Template
metadata: 
  name: oc-python-app-template
labels:
  app: python-app
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: python-app
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: python-app
      template:
        metadata:
          labels:
            app: python-app
        spec:
          containers:
            - name: oc-python-app
              image: quay.io/andrewocamps/oc-python-app:latest
              ports:
                - containerPort: 8080
                  protocol: TCP
          restartPolicy: Always
  - kind: Service
    apiVersion: v1
    metadata:
      name: python-app
    spec:
      ports:
        - name: python-app
          port: 8080
          targetPort: 8080
      selector:
        app: python-app 
   