apiVersion: v1
kind: Template
metadata: 
  name: oc-python-app-template
objects:
  - kind: Pod
    apiVersion: v1
    metadata:
      name: oc-python-app
    labels:
      app: oc-python-app
    spec:
      containers:
        - image: quay.io/andrewocamps/oc-python-app
          name: oc-python-app
          ports:
            - containerPort: 8080
  - kind: Service
    apiVersion: v1
    metadata:
      name: oc-python-app
    spec:
      ports:
        - name: oc-python-app
          port: 8080
          targetPort: 8080
      selector:
        app: oc-python-app 
   