---
apiVersion: v1
kind: ReplicationController
metadata:
  name: python-app-1
spec:
  replicas: 2
  selector:
    app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: oc-python-app
          image: quay.io/andrewocamps/oc-python-app:latest
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
          