---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: python-app
spec:
  replcias: 3
  selector:
    app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: oc-python-app
          image: quay.io/andrewocamps/oc-python-app:latest
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - oc-python-app
      from:
        kind: ImageStreamTag
        name: oc-python-app:latest
    type: ImageChange
  strategy:
    type: Rolling
